name: SSL Expiry Check

on:
  workflow_dispatch:
    schedule: 
      - cron: 0 0 * * *
jobs:
  check_ssl_expiry:
    runs-on: ubuntu-latest

    steps:
      - name : checkout repo
        uses: actions/checkout@v2

      - name: Run SSL Script
        run: |
         chmod +x /scripts/ssl_chk.sh
         .//scripts/ssl_chk.sh ${{ secrets.TEST_SECRET }}
